repos:
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: flake8
-   repo: local
    hooks:
    -   id: tests
        name: run tests and coverage
        entry: coverage run -m pytest -v
        language: system
        types: [python]
        stages: [push]
    -   id: cov_badge
        name: produce coverage badge
        entry: coverage-badge -o images/coverage.svg
        language: system
        types: [python]
        stages: [push]
