-   id: tests
    name: run tests and coverage
    entry: coverage run -m pytest -v
    language: system


-   id: cov_badge
    name: produce coverage badge
    entry: coverage-badge -o images/coverage.svg
    language: system
