name: IPS
channels:
  - defaults
dependencies:
  - python=3.6.*
  - pip
  - matplotlib
  - numba
  - numpy
  - pandas
  - pathlib
  - pyarrow
  - seaborn
  - scipy
  - pip:
    - coolname
    - datetime
    - pre-commit
